version: '3.0'
services:
    db:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - ./mysql/datadir:/var/lib/mysql
        restart: always
        image: "mysql:8.0"
        networks:
            app_net:
                ipv4_address: 172.18.0.2
        container_name: db
    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        image: "redis:5.0"
        networks:
            app_net:
                ipv4_address: 172.18.0.5
        container_name: redis
    fpm:
        depends_on:
            - db
            - redis
        build:
            context: ./fpm
            dockerfile: Dockerfile
        volumes:
            - /home/cwhsu/docker-demo/app:/usr/share/nginx/html
        restart: always
        links:
            - db:mysql
        image: "fpm:7.2"
        networks:
            app_net:
                ipv4_address: 172.18.0.3
        container_name: fpm
    web:
        depends_on:
            - fpm
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        restart: always
        image: "nginx:0.1"
        networks:
            app_net:
                ipv4_address: 172.18.0.4
        container_name: myweb

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.18.0.0/24
